---
title: "Lab 6"
author: "Logan Kozal"
date: "2/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(gstat) #for variogram?
library(stars) #for grid
```

```{r}
ca_dgw <- read_sf(here::here("ca_dgw"), layer = "F2013_DBGS_Points_20150720_093252") %>% 
  clean_names()

st_crs(ca_dgw)

ca_counties <- read_sf(here("ca_counties"), layer= "CA_Counties_TIGER2016") %>%
  clean_names() %>% 
  select(name)

st_crs(ca_counties)

#use st tranform because it already has a ref system

ca_counties <- st_transform(ca_counties, st_crs(ca_dgw))

st_crs(ca_counties)
```

```{r}
ggplot()+
  geom_sf(data = ca_counties)+
  geom_sf(data = ca_dgw, aes(color = dgbs))
```

```{r}
tmap_mode("view")

tm_shape(ca_dgw)+
  tm_dots("dgbs")
```

```{r}
sj_county <- ca_counties %>% 
  filter(name == "San Joaquin")

#now find observations that fit within those county borders

sj_depth <- ca_dgw %>% 
  st_intersection(sj_county)

plot(sj_depth)
plot(sj_county)

ggplot()+
  geom_sf(data = sj_county)+
  geom_sf(data = sj_depth, aes(color = dgbs))

```

```{r}
well_duplicates <- sj_depth %>% 
  get_dupes(latitude, longitude) 

# probably would normally just average these in the real world rather than removing

sj_depth <- sj_depth %>% 
  filter(!local_well %in% well_duplicates$local_well)

sj_depth %>% 
  get_dupes(latitude, longitude) 

```

```{r}
sj_dgw_vgm <- variogram(dgbs ~ 1, data = sj_depth)

plot(sj_dgw_vgm)

#but want a continuous function

sj_dgw_vgm_fit <- fit.variogram(sj_dgw_vgm, model = vgm(nugget = 20, psill = 3000, range = 30, model = "Gau")) #gaussian, can try others

sj_dgw_vgm_fit 

plot(sj_dgw_vgm, sj_dgw_vgm_fit)
```
### Spatial kriging (interpolation)
```{r}
#make a grid, bbox is bounding box
sj_grid <- st_bbox(sj_county) %>% 
  st_as_stars(dx = 0.01, dy = 0.01) %>% 
  st_set_crs(4326) %>% 
  st_crop(sj_county)

plot(sj_grid)

```
```{r}
# ~1 for constant but unknown field (ordinary kriging)
sj_dgw_krige <- krige(dgbs ~ 1, sj_depth, sj_grid, model = sj_dgw_vgm_fit)

plot(sj_dgw_krige)

#converting to points or raster in the key file

# Convert it to a spatial data frame
krige_df <- as.data.frame(sj_dgw_krige) %>% 
  st_as_sf(coords = c("x","y")) %>% 
  drop_na(var1.pred)

st_crs(krige_df) <- 4326

# Then we can use ggplot: 
ggplot(data = krige_df) +
  geom_sf(aes(color = var1.pred)) +
  scale_color_gradient(low = "blue", high = "yellow")
```

